name: Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    environment: production
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-24.04
    environment: production
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test

  build-and-push-image:
    needs: [lint, test]
    runs-on: ubuntu-24.04
    if: ${{ success() }}
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t ${{ secrets.DOCKER_HUB_USER }}/telegram-ui-vue:latest
      - name: Push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/telegram-ui-vue:latest

  pull-and-run-image:
    needs: [lint, test, build-and-push-image]
    runs-on: ubuntu-24.04
    if: ${{ success() }}
    environment: production
    steps:
      - name: Pull and run image on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop telegram-ui-vue || true
            docker rm telegram-ui-vue || true
            docker pull ${{ secrets.DOCKER_HUB_USER }}/telegram-ui-vue:latest
            docker run -d -p 8003:80 --name telegram-ui-vue --restart=always ${{ secrets.DOCKER_HUB_USER }}/telegram-ui-vue:latest
          EOF

  release:
    needs: [lint, test]
    runs-on: ubuntu-24.04
    if: ${{ success() }}
    environment: production
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
